services:

  postgres:
    image: postgres:14
    container_name: orders-service
    environment:
      POSTGRES_DB: orders-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build:
      context: ./../../cmd/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/userdb?sslmode=disable
    ports:
      - "50051:50051"

  order-service:
    build:
      context: ./../../order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - postgres
      - user-service
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/orderdb?sslmode=disable
      - USER_SERVICE_URL=user-service:50051
    ports:
      - "50052:50052"

volumes:
  postgres_data:
