version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: orders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./../../user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/userdb?sslmode=disable
    ports:
      - "50051:50051"

  order-service:
    build:
      context: ./../../order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - postgres
      - user-service
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/orderdb?sslmode=disable
      - USER_SERVICE_URL=user-service:50051
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "50052:50052"

volumes:
  postgres_data: