// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/NTsareva/orders-users-simple-service/cmd/order-service/ent/order"
	"github.com/NTsareva/orders-users-simple-service/cmd/order-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescTitle is the schema descriptor for title field.
	orderDescTitle := orderFields[1].Descriptor()
	// order.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	order.TitleValidator = orderDescTitle.Validators[0].(func(string) error)
	// orderDescDescription is the schema descriptor for description field.
	orderDescDescription := orderFields[2].Descriptor()
	// order.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	order.DescriptionValidator = orderDescDescription.Validators[0].(func(string) error)
	// orderDescUserID is the schema descriptor for user_id field.
	orderDescUserID := orderFields[3].Descriptor()
	// order.DefaultUserID holds the default value on creation for the user_id field.
	order.DefaultUserID = orderDescUserID.Default.(int)
	// order.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	order.UserIDValidator = orderDescUserID.Validators[0].(func(int) error)
}
